import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/navbar/Navbar";
import { dbConnect } from "@/lib/connectDb";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ecommerce App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const conn = await dbConnect();
  // console.log(conn)

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        </body>
    </html>
  );
}
