import { Inter } from "next/font/google";
import Link from "next/link";
import Styles from './admin.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ecommerce App Admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

      <div className={Styles.contain}>

        <div className={Styles.container}>
          <h1 className={Styles.title}>Admin Page</h1>
          <div>
            <ul className={Styles.ul}>
              <li className={Styles.li}><Link className={Styles.link}  href="/admin/home">Home</Link></li>
              <li className={Styles.li}><Link className={Styles.link}  href="/admin/addcategory">Add category</Link></li>
              <li className={Styles.li}><Link className={Styles.link}  href="/admin/addproducts">Add Products</Link></li>
              <li className={Styles.li}><Link className={Styles.link}  href="/admin/viewuser">Users</Link></li>
            </ul>
          </div>
        </div>

          <div>
            {children}
          </div>

      </div>
      
      </body>
    </html>
  );
}
